language: 'python'

install: 'pip install -r requirements.txt'

script:
  - 'make html'
  - 'touch build/html/.nojekyll'

deploy:
  github_token: '$GITHUB_TOKEN'
  keep-history: true
  local_dir: 'build/html/'
  on:
    branch: 'master'
  provider: 'pages'
  skip_cleanup: true
  target_branch: 'gh-pages'
