# Making changes? https://github.com/nektos/act may help you test locally

name: Build to artifact

on: [push, pull_request] # TODO: Only build for branches that aren't master, publish on master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      env:
        SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        docs-folder: "."
    - uses: actions/upload-artifact@v1
      with:
        name: docs-html
        path: build/html/

